#!/usr/bin/python2
# coding: utf8

""" @author: Tristan piratClassif """

import os
import glob
import subprocess

def launchMCL():
	"""

	Launch the MCL on all the prelibraries created by the save module in order to obtain superfamilies. For this, it execute bash script that will do the work.

	@rtype: None
	"""
	#### This part is dedicated to the family classification using the MCL of REPET package
	#### First made the script executable
	subprocess.call(["chmod", "0744", "/home/jeremy/galaxy/tools/Pipeline/pirateClassif/MCL/database.sh"])
	#### Then execute the script
	subprocess.Popen("/home/jeremy/galaxy/tools/Pipeline/pirateClassif/MCL/database.sh", shell=True).wait()

	#### First made the script executable
	subprocess.call(["chmod", "0744", "/home/jeremy/galaxy/tools/Pipeline/pirateClassif/MCL/launch.sh"])
	#### Then execute the script
	subprocess.Popen("/home/jeremy/galaxy/tools/Pipeline/pirateClassif/MCL/launch.sh", shell=True).wait()

def saveLibraries():
	"""

	Creates the three libraries, according the research paper PiRATE :
		- 1 for autonomous TE
		- 1 for all TE
		- 1 for all repeated elements
	For this, it uses the sequences generated by the MCL script.

	@rtype: None
	"""
	#TODO
	listFiles=[]
	listClassification=[]
	for(rep, subRep, files) in os.walk("/home/jeremy/galaxy/tools/Pipeline/pirateClassif/MCL/WORK"):
		#### Retrieve the classification name of MCL sequences, from the file name
		try :
			listClassification.append(subRep)
			listFiles.append(files)
		except (FileNotFoundError, NameError) as e:
			print("/!\ Error this file does not exist : %s"%(e))
	#### Use the find bash command to retrieve all the classification name of the libraries
	bashCommand = subprocess.Popen('find /home/jeremy/galaxy/tools/Pipeline/pirateClassif/MCL/WORK/ -name "*_MCL.fa" 2> /dev/null', shell=True, stdout=subprocess.PIPE);
	MCLsequences = bashCommand.stdout.read()
	print(MCLsequences)

	# for files in listeFiles:
	#     if file
	#
	# print(listFiles)
	# print(listClassification[0])
	# for name in glob.glob("/home/jeremy/galaxy/tools/Pipeline/classification/MCL/WORK/*"):
	#     print (name)
